// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0--rc3
// source: protos/graph_auth/graph_auth.proto

package graph_auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokensGenerater_GenerateAuthTokens_FullMethodName = "/graph_auth.TokensGenerater/GenerateAuthTokens"
)

// TokensGeneraterClient is the client API for TokensGenerater service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokensGeneraterClient interface {
	GenerateAuthTokens(ctx context.Context, in *AuthTokensRequest, opts ...grpc.CallOption) (*AuthTokensResponce, error)
}

type tokensGeneraterClient struct {
	cc grpc.ClientConnInterface
}

func NewTokensGeneraterClient(cc grpc.ClientConnInterface) TokensGeneraterClient {
	return &tokensGeneraterClient{cc}
}

func (c *tokensGeneraterClient) GenerateAuthTokens(ctx context.Context, in *AuthTokensRequest, opts ...grpc.CallOption) (*AuthTokensResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthTokensResponce)
	err := c.cc.Invoke(ctx, TokensGenerater_GenerateAuthTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokensGeneraterServer is the server API for TokensGenerater service.
// All implementations must embed UnimplementedTokensGeneraterServer
// for forward compatibility.
type TokensGeneraterServer interface {
	GenerateAuthTokens(context.Context, *AuthTokensRequest) (*AuthTokensResponce, error)
	mustEmbedUnimplementedTokensGeneraterServer()
}

// UnimplementedTokensGeneraterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokensGeneraterServer struct{}

func (UnimplementedTokensGeneraterServer) GenerateAuthTokens(context.Context, *AuthTokensRequest) (*AuthTokensResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateAuthTokens not implemented")
}
func (UnimplementedTokensGeneraterServer) mustEmbedUnimplementedTokensGeneraterServer() {}
func (UnimplementedTokensGeneraterServer) testEmbeddedByValue()                         {}

// UnsafeTokensGeneraterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokensGeneraterServer will
// result in compilation errors.
type UnsafeTokensGeneraterServer interface {
	mustEmbedUnimplementedTokensGeneraterServer()
}

func RegisterTokensGeneraterServer(s grpc.ServiceRegistrar, srv TokensGeneraterServer) {
	// If the following call pancis, it indicates UnimplementedTokensGeneraterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokensGenerater_ServiceDesc, srv)
}

func _TokensGenerater_GenerateAuthTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokensGeneraterServer).GenerateAuthTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokensGenerater_GenerateAuthTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokensGeneraterServer).GenerateAuthTokens(ctx, req.(*AuthTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokensGenerater_ServiceDesc is the grpc.ServiceDesc for TokensGenerater service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokensGenerater_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graph_auth.TokensGenerater",
	HandlerType: (*TokensGeneraterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateAuthTokens",
			Handler:    _TokensGenerater_GenerateAuthTokens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/graph_auth/graph_auth.proto",
}
