package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"sort"

	pb "github.com/peygy/nektoyou/internal/pkg/protos/graph_auth"
	"github.com/peygy/nektoyou/internal/services/graphql/graph/model"
)

// RegisterUser is the resolver for the registerUser field.
func (r *mutationResolver) RegisterUser(ctx context.Context, input model.UserInput) (*model.AuthPayload, error) {
	authConnIdx := sort.Search(len(r.GrpcServices), func(i int) bool { return r.GrpcServices[i].Name == "auth_service" })
	cl := pb.NewTokensGeneraterClient(r.GrpcServices[authConnIdx].Conn)

	responce, err := cl.GenerateAuthTokens(ctx, &pb.AuthTokensRequest{Username: input.Username, Password: input.Password})
	if err != nil {
		fmt.Print(err)
		return nil, fmt.Errorf("could not create tokens: %v", err)
	}

	return &model.AuthPayload{
		AccessToken:  responce.GetAccessToken(),
		RefreshToken: responce.GetRefreshToken(),
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
